version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_CONTAINER_PORT
    volumes:
      - db_trabalho:/data/db
  app:
    
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - "./src:/app/"
      - "/app/node_modules"
    ports:
      - $NODE_LOCAL_PORT:$NODE_CONTAINER_PORT
    depends_on:
      - mongodb

volumes:
  db_trabalho: